package sdk.hhyk.com.libhhyk_sdk;


public class PayConfig {
	



//	public static final String MERCHANT_ID = "311054";//平台为商户分配的唯一编号
//	public final static String URL_PAYAPI_ORDER = "https://cp.halocash.hk/halocash/v1/createtrans";
//	public final static String PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCpPOLKWd71NlGVUUfY9FcEQlUTjK5f8BYiGrGqcWg0MpqZLMFuXOnH1V6mBg+pk7MPbzB1rZl2QUDKyc8PMuVLYplAi7WTBpDui/SO+4Hxu/Y6rBAP2eozQgZuYO6XBUdRuRm7mUryAsKrCFX6lH0oqa/TT31m4KMPfNIbvsG8awIDAQAB";
//	public final static String NOTIFY_URL = "http://www.iapppay.com/test";
//	public static final	String PRIVATE_KEY ="MIICWwIBAAKBgQCFxfvFYM/fHRYIXcIVzsNwBRgZQGfZm7qQpKLiGbqN5sc4fIGn98Cg9lkvrfwvpOrxZQlONxfqFfrpHwLYFLnR7/eC7NoTWeIcGxJdjrViyPQ+wAUtj2SSeebCBApY4s7Ko3Wqfm7eqzkss7v1sQgRZ0225eoAl9TWQPhLy/yEMwIDAQABAoGAZrVh32O7dmSQnA/QionbyFBA9nJaydslXRTq8ooqj/TWlOoTanFwdqVuSItfCv2mXXzjrifitpn1sbNbragMGqU/BV86TQDfneG43xb+xTWf7nPvnvcRIhBuIzFzddoBP7Q4l9ePZkQ8RUaPBV/iHvrNsykD3TveW6WMWB9VN4ECQQDGC2ntk4R6eaYKgVpqWMDFcOCFusZl+/4k1GYNVXCupvWB6SU2np8SHcGgBut9qkKnByW+IRJfhbCZ3gzofjfTAkEArOuqyZJ27JzHVoxZDXp0oUPVTK/qzlwMQqx8dzT/QOOzR9OqeGy29L40eODn5SlpIs9Fq+ffUISr6oYlZBomIQJAALmp+aTAp3IqmX8/xYPtsMtpBxRYBaeWlqvwc7wMXZde7srbyAdsrbROMTfVRPCKrfHowXl9h7wFmYqmoXNU4QJAQyyNvR5zqnlBCsMcuRqwAhGq486XBbFGZgRBmcFxw1BxTd7RI1UAQdU95xNfomtS113zr9M0sj/H1SRllByAYQJACMPbmYZr6xw2Brk4eB5CzIHFXhXIa/aa7Fxs+zKdB8Yp/MWXJ17ZH1hWwy/mMUxWOwnq5XhclrioyLtWPdrDsw==";


	public static final String MERCHANT_ID = "3785";//平台为商户分配的唯一编号
	public final static String URL_PAYAPI_ORDER = "https://cp.halocash.hk/halocash/v1/createtrans";
	public final static String URL_PAYAPI_WEB ="https://webpay.halocash.hk/halocash/v1/gateway";
	public final static String PRIVATE_KEY = "MIICXQIBAAKBgQC8U+Rh12CLFlUydxlkhCXp41+0MQMa4uFXEQf2hLCNDIh+fD2tbp6cgOw0cqicjNpikgcrm2n6vh9/N4QZdAFh8dcau5YAr35UKQ4vV8y6e6fpEt8p660KdOyUcIXwrkGg3CfdrQNodBk2MYxUTs9LGo5kqKx3bhGIoK34lCLwXwIDAQABAoGAKJtiLCKXg4X+OtJpXD4OOr83HJBQ3hQ7iF14vRPhSZiBOdyqI+ItOwulYq2yY4cPc5+PAj0RfepOukyLJD3aKhiDHMi9cXCfRaMKdmbci1N7RosVNfhI/0BJFu1ApwOottNG9ctsH+d3VQf0wEwsZfRO0DnxsKq4Yss0zHszSAECQQDmIxAISntLKNDjtLZYvjVGsDTxUZN/tmZzP6iqXX6FBXQ2ayAd8YIIUqGxF5lobX36kWmFI7XW6Y5vzmvi0HQBAkEA0X3+7XGiYG0YanfBQYap36XDfLM7akLYhTFh/oHKSm3JMIwmyfeW5fcWFOwTMxwR2FMhyPkMJjgE2cKD1XfkXwJBANOuIpwNrlSWqXUZDrSX2Dc58qiZSVuqcZfGUSTLNIm0V42KgZMpRlrTbqiOtWupcrwcLnvpOeQBFiPfMbsB1AECQQCiMI0U4hxX0T7M9whdJdgQ+bI+sjj2zOf7Pr9inrOyKgtQlcFWLmTaiBDFg/xdXocGV15ZzU81q7s9qJYOyDK7AkByRQFk3A/pE0CNbEfegiz2ZUQAxNVXXCB8F6kzm/qopKHhhwdSjVng3iO1kZ667pfuTqxw5YwwMuQ83dPJ0Jpq";
	public final static String PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2WG3jgNIGWCQlSO1Iai2k75PcAtYIG0DgpwX3SuWkprBBVoBAWlc53q/Hp/ZS6aMCLktha9LZ+0a9hYkOS7ygQfVTO2D92m0hiGpkrFKR0y1KNN8Rv4WTvgWDGFhmTWvX/QH/hgN6YbJunvtA3JVwxg/IvRb2VI1MIyfOaB7CHwIDAQAB";
	public final static String NOTIFY_URL = "http://www.iapppay.com/test";

}
